catalogs:
  shiki:
    '@shikijs/transformers': 3.4.2
    shiki: 3.4.2
  next:
    next: 15.3.1
    '@next/bundle-analyzer': 15.3.1
  react:
    react: 19.1.0
    react-dom: 19.1.0
    '@types/react': 19.1.5
    '@types/react-dom': 19.1.5
  test:
    vitest: 3.1.4
    '@vitest/web-worker': 3.1.4
    '@vitest/coverage-v8': 3.1.4
  three:
    three: 0.176.0
    '@types/three': 0.176.0

ignoredBuiltDependencies:
  - '@biomejs/biome'
  - 'sharp'
