catalogs:
  shiki:
    '@shikijs/transformers': 3.4.2
    shiki: 3.4.2
  next:
    next: 15.3.1
    '@next/bundle-analyzer': 15.3.1
  react:
    react: 19.1.0
    react-dom: 19.1.0
  react-type:
    '@types/react': 19.1.4
    '@types/react-dom': 19.1.5

ignoredBuiltDependencies:
  - '@biomejs/biome'
