import type { Metadata } from 'next'
import { ViewTransitions } from 'next-view-transitions'
import { ThemeProvider } from 'next-themes'
import Header from './components/Header'
import Modal from './posts/components/Modal'
import './globals.css'
import './variable.css'
import Footer from './components/Footer'
import Float from './components/Float'
import { noto } from './fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <ViewTransitions>
        <body className={noto.className}>
          <ThemeProvider>
            <Header />
            {children}
            <Footer />
            <Float />
            <Modal />
          </ThemeProvider>
        </body>
      </ViewTransitions>
    </html>
  )
}
